<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUanrxin\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUanrxin/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUanrxin.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUanrxin\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUanrxin\appProdProjectContainer([
    'container.build_hash' => 'Uanrxin',
    'container.build_id' => '3f97c263',
    'container.build_time' => 1606443027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUanrxin');
